Assing IP Interface In DMZ_SW
Interface              IP-Address      OK? Method Status                Protocol
Ethernet0/0            172.168.254.2   YES manual up                    up      
Ethernet0/1            172.168.254.5   YES manual up                    up      
Loopback0              172.168.255.1   YES manual up                    up      

router ospf 10
 router-id 172.168.255.1
 network 172.168.254.2 0.0.0.0 area 5
 network 172.168.254.5 0.0.0.0 area 6
interface Ethernet0/1
 description Uplink_DMZ_SVR
 no switchport
 ip address 172.168.254.5 255.255.255.252
 ip ospf authentication key-chain DMZ
 ip ospf network point-to-point
 ip ospf dead-interval 3
 ip ospf hello-interval 1
end
interface Ethernet0/0
 description Downlink_CoreSw
 no switchport
 ip address 172.168.254.2 255.255.255.252
 ip ospf authentication key-chain DMZ
 ip ospf network point-to-point
 ip ospf dead-interval 3
 ip ospf hello-interval 1

# Configuration Backbone Area 0 with Connet Area 6 within Virtual-link
area 5 virtual-link 1.1.1.1 hello-interval 1 dead-interval 3 authentication key-chain DMZ
