#Assign Interface Ip add in DMZ_SVR

Interface                  IP-Address      OK? Method Status                Protocol
Ethernet0/0                172.168.254.6   YES manual up                    up      
Loopback0                  172.168.255.2   YES manual up                    up      
Loopback1                  172.168.0.1     YES manual up                    up      
Loopback2                  172.168.1.1     YES manual up                    up      
Loopback3                  172.168.2.1     YES manual up                    up      
Loopback4                  172.168.3.1     YES manual up                    up      
Loopback5                  172.168.4.1     YES manual up                    up      
Loopback6                  172.168.5.1     YES manual up                    up      
Loopback7                  172.168.6.1     YES manual up                    up      
Loopback8                  172.168.7.1     YES manual up                    up    
interface Ethernet0/0
 description Downlink_DMZSW
 ip address 172.168.254.6 255.255.255.252
 ip ospf authentication key-chain DMZ
 ip ospf network point-to-point
 ip ospf dead-interval 3
 ip ospf hello-interval 1
 duplex auto
end
#Routing OSPF in DMZ_SVR

router ospf 10
 router-id 172.168.255.2
 #Type1 with win to choose!
 redistribute connected metric-type 1 subnets route-map Connect_TO_OSPF
 network 172.168.254.6 0.0.0.0 area 6

#External route summization in ASBR 
summary-address 172.168.0.0 255.255.248.0
