#Configuration R2

en
conf t
int e0/0
ip add 10.0.255.22 255.255.255.252
no shut
des Downlink_Coresw
int e0/1
ip add 198.0.0.2 255.255.255.252
no shut
des Uplink_ISP2
int lo0
ip add 3.3.3.3 255.255.255.255
no shut
exit
int e0/2
ip add  196.0.0.2 255.255.255.252
no shut
des Uplink_ISP3
do wr
# Routing OSPF on R2
router ospf 10
router-id 3.3.3.3
network 10.0.255.22  0.0.0.0 area 0
exit
int e0/0
ip os hell 1
ip os dead 3
ip os net point-to-point
exit
key chain R2
key 1
key-string ccnpospf
crypto-al  hmac-sha-512
service password-encryption
int e0/0
ip os authen key-chain R2
exit
do wr
# Configuration Default Route 
ip sla 1 
icmp-echo 197.0.0.1
fre 5
thre 250
time 300
exit
ip sla sch 1 start no lif fo
track 1 ip sla 1
delay up 1 do 1
exit
do sh ip sla sum
do sh track
ip route 0.0.0.0 0.0.0.0 196.0.0.1 name ISP3 track 1
ip route 0.0.0.0 0.0.0.0 198.0.0.1 name ISP2 10
#configuration ACL For NAT
Extended IP access list NAT_ACL
    10 permit ip 10.0.0.0 0.0.7.255 any
    20 permit ip 172.168.0.0 0.0.7.255 any
route-map ISP2 permit 10
 match ip address NAT_ACL
route-map ISP3 permit 10
 match ip address NAT_ACL
int e0/1

 ip nat outside
 int e0/2
 ip nat outside
 int e0/0
 ip nat inside
 ip nat inside source route-map ISP2 interface Ethernet0/1 overload
ip nat inside source route-map ISP3 interface Ethernet0/2 overload

router ospf 10
 router-id 3.3.3.3
 network 10.0.255.22 0.0.0.0 area 0
 default-information originate metric-ty 2
